name: pdf_scanner_app
description: "Flutter PDF Scanner App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera & Image
  image_picker: ^1.0.7

  # PDF creation
  pdf: ^3.10.7

  # File system
  path_provider: ^2.1.2

  # Permissions
  permission_handler: ^11.3.0

  # Open generated PDF
  open_file: ^3.3.2

  # Share files
  share_plus: ^7.2.2

  # OCR
  google_mlkit_text_recognition: ^0.13.0

  # State management
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/scanner.png
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/scanner.png
